# Gesturer Configuration Elements
#

# Object Information
#
# NOTE: Each object index value denotes on specific individual servo. That is,
# all of the values in the first position of each list apply to the same
# distinct servo, all of the values in the second position of each list
# apply to the same distinct servo, etc. 

# Total number of Blender objects/Arduino servos in use
numObjects: 2
# Name of each object to extract rotation information from and transmit to servos.
objectNames:
    - Cube.001
    - Cube
# Axis of rotation to be extracted from each Blender object
objectAxes:
    - 0
    - 1
# Multiplier applied directly to the axis movement values from Blender before
# the objectOffsets are added to get the final servo angle value.
objectMultipliers:
    - '1'
    - '1'
# Values added to the movement values from Blender (after the multiplier is applied)
objectOffsets:
    - 90
    - 90
# Pin each individual servo is connected to on the Arduino
servoPins:
    - 13
    - 7

# Arduino information
# 

# Port to connect to the Arduino with via USB
serialPort: /dev/tty.usbmodem1431


# All following information is used for Arduino code generation and may be 
# ignored by the user.

# Motor identifcation schema for Arduino code generation
motorIdentification: switching

# Offsets for insertion locations of code within automatic generation
switchingOffsets:
    2: servoObjects  
    3: numServos  
    4: servoPins  
    10: attachServos
    24: exceedsUpperBound  
    26: servoSwitch 
    27: currentServoIncrement 
# Offsets for insertion locations of code within automatic generation
addressingOffsets:
    2: servoObjects  
    3: numServos  
    4: servoPins  
    10: attachServos
    24: receiveAddressByte
    25: addressingSwitch 
